---
- name: MongoDB Lead -  copy file for Create Super Admin User
  template:
      src: setupuser.js.j2
      dest: /tmp/setupuser.js
      mode: '0666'

- name: MongoDB Lead - Execute the create super admin user script
  shell: mongo --host "mongodb://localhost:{{ mongodb_port }}/admin" /tmp/setupuser.js
  # We'll ignore, the error. As we'll try to run this on all the replicasets, but it'll succeed only on the primary. 
  ignore_errors: yes 

- name: MongoDB Lead - Clean Setup files
  shell: rm /tmp/setupuser.js
  ignore_errors: yes # These files are 
  
