---
# tasks file for initiating replica
- name: MongoDB Lead -  copy file for initialization script
  template:
      src: initreplica.js.j2
      dest: /tmp/initreplica.js
      mode: '0666'

- name: MongoDB Lead - Execute the initialization script and add all replicants
  shell: mongo --port {{ mongodb_port }} /tmp/initreplica.js

- name: MongoDB Lead -  copy file for Create Super Admin User
  template:
      src: setupuser.js.j2
      dest: /tmp/setupuser.js
      mode: '0666'

- name: MongoDB Lead - Execute the create super admin user script
  shell: mongo --host mongodb://{{ mongodb_replica_set_complete_host_name }}/admin?replicaSet={{ replica_set_name }} /tmp/setupuser.js

- name: MongoDB Lead - Clean Setup files
  shell: rm /tmp/initreplica.js /tmp/setupuser.js
