---
# tasks file for installation
- name: MongoDB - Copy hosts data
  blockinfile:
    dest: /etc/hosts
    block:  "{{ lookup('file', 'etc_hosts') }}" 

- name: MongoDB - Import public key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present

- name: MongoDB - Add repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
    state: present
    filename: mongodb-org-5.0.list
    mode: '0666'

- name: MongoDB - Install
  apt:
    name: mongodb-org
    state: latest
    update_cache: yes

- name: MongoDB - Generate random string for mongodb keyfile
  local_action: ansible.builtin.command openssl rand -base64 756
  become: false
  register: mongodb_keyfile
  run_once: True
  
- name: MongoDB - Copy keyfile for internal authentication
  template:
      force: yes
      src: mongodbkeyfile.j2
      dest: /etc/mongod.keyfile
      owner: mongodb
      group: mongodb
      mode: '0400'

- name: MongoDB - Copy configuration file
  template:
    force: yes
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify: Restart mongodb

- name: MongoDB - Ensure mongodb is running and enabled to start automatically after reboots
  systemd:
    name: mongod
    enabled: yes
    state: started