- hosts: mongodb
  become: yes
  become_user: root
  roles:
    - installation
    
- hosts: mongodb_lead
  become: yes
  become_user: root
  roles:
    - initreplica

- hosts: mongodb 
  become: yes
  roles: 
    - setupuser
  vars_prompt:
  - name: "mongodb_admin_user"
    prompt: "Enter Mongodb Super Admin Username"
    # private: yes
  - name: "mongodb_admin_pass"
    prompt: "Enter MongoDb Super Admin Password"
    private: yes
  